### ISSUE TITLE
Correct zmDifficulty values

### ISSUE THREAD

**Issue by SoyRA** [xerxes-at/T6ServerConfigs#1]
https://github.com/xerxes-at/T6ServerConfigs/blob/2b8498eadca7727e46502294563daebbf6aa3414/dedicated_zm.cfg#L42

I was wrong, the right values are:
```c
//gts zmDifficulty 1                            // Difficulty? 0 = Easy, 1 = Normal
```

**Comment by xerxes-at** [comment]
Fixed in c8a6e62.
