### ISSUE TITLE
Codes for ZM maps

### ISSUE THREAD

**Issue by SoyRA** [xerxes-at/T6ServerConfigs#2]
- Well, the first time I sent you my CFG I had commented on the "unsupported" maps. But today I checked to put the correct code (working or not, on dedicated server).
  * Assuming they're the same codes you get inside the game...the "verified" maps gave me the same result, so I'm confident the others are fine. :P

```c
// [No DLC] Green Run -> Bus Depot -> TranZit  -> gametype zclassic loc transit map zm_transit
// [No DLC] Green Run -> Bus Depot -> Survival -> gametype zstandard loc transit map zm_transit
// [No DLC] Green Run -> Town      -> Grief    -> gametype zgrief loc town map zm_transit
// [No DLC] Green Run -> Town      -> Survival -> gametype zstandard loc town map zm_transit
// [No DLC] Green Run -> Farm      -> Grief    -> gametype zgrief loc farm map zm_transit
// [No DLC] Green Run -> Farm      -> Survival -> gametype zstandard loc farm map zm_transit
// [DLC 1 ] Green Run -> Diner     -> Turned   -> gametype zcleansed loc diner map zm_transit_dr


// [DLC 2] Alcatraz Prison -> Sunset Strip -> Mob of the Dead -> gametype zclassic loc prison map zm_prison
// [DLC 2] Alcatraz Prison -> Cell Block   -> Grief           -> gametype zgrief loc cellblock map zm_prison


// [Bonus Map] Nevada, U.S.A. -> Nuketown -> Survival -> gametype zstandard loc nuked map zm_nuked


// [DLC 4] Excavation Site 64 -> Origins -> Origins -> gametype zclassic loc tomb map zm_tomb


// [DLC 3] Resolution 1295 -> Processing -> Buried -> gametype zclassic loc processing map zm_buried
// [DLC 3] Resolution 1295 -> Borough    -> Grief  -> gametype zgrief loc street map zm_buried
// [DLC 3] Resolution 1295 -> Borough    -> Turned -> gametype zcleansed loc street map zm_buried


// [DLC 1] Great Leap Forward -> Skyscraper -> Die Rise -> gametype zclassic loc rooftop map zm_highrise
```

But some don't work, and give the same error:
```c
// [No DLC] Green Run -> Bus Depot -> Survival -> gametype zstandard loc transit map zm_transit
// [No DLC] Green Run -> Town      -> Grief    -> gametype zgrief loc town map zm_transit
// [No DLC] Green Run -> Town      -> Survival -> gametype zstandard loc town map zm_transit
// [No DLC] Green Run -> Farm      -> Grief    -> gametype zgrief loc farm map zm_transit
// [No DLC] Green Run -> Farm      -> Survival -> gametype zstandard loc farm map zm_transit
**** 8 script error(s):
**** Unresolved external :  "precache" with 0 parameters in "maps/mp/zm_transit.gsc" at line 1 ****
**** Unresolved external :  "precache" with 0 parameters in "maps/mp/zm_transit.gsc" at line 1 ****
**** Unresolved external :  "precache" with 0 parameter



// [DLC 3] Resolution 1295 -> Borough    -> Grief  -> gametype zgrief loc street map zm_buried
// [DLC 3] Resolution 1295 -> Borough    -> Turned -> gametype zcleansed loc street map zm_buried
**** 2 script error(s):
**** Unresolved external :  "precache" with 0 parameters in "maps/mp/zm_buried.gsc" at line 1 ****
**** Unresolved external :  "main" with 0 parameters in "maps/mp/zm_buried.gsc" at line 1 ****
```

So the only "new" thing would be:
- Alcatraz Prison - Cell Block - Grief (gametype zgrief loc cellblock map zm_prison)
  * Which I admit I haven't tried to join, I know the server doesn't close and says it's running. a,a

I do this for pure information (assuming it's correct), in case you want to implement such maps or whatever in the future.\
  \* Although I've seen two servers in "Green Run - Town - Survival", I guess they had to edit something (and they don't share it for some security reason...or I don't know).

**Comment by xerxes-at** [comment]
I do know about them and your values are correct, but I did not include them as they don't work and require an update of PlutoT6, certain people just won't read everything and just spam the support threads about why the maps don't work.

**Comment by JezuzLizard** [comment]
This issue can be closed since the codes for all zm maps/gamemodes are available in the latest commit.

**Comment by AlexJaen** [comment]
> 
> 
> This issue can be closed since the codes for all zm maps/gamemodes are available in the latest commit.

Hi, where can I found it? I would like to have these codes.

**Comment by Luizdoufera** [comment]
I have the same problem, did anyone manage to solve it?

**Comment by AlexJaen** [comment]
As JezuzLizard said, the map codes are now inside the config server files.
Image of dedicated_zm.cfg
![2](https://github.com/xerxes-at/T6ServerConfigs/assets/49147488/0aaa512d-a9d0-49c6-a985-bd153edb6ca2)
