### ISSUE TITLE
Restrict weapon attachment not working

### ISSUE THREAD

**Issue by bugge** [xerxes-at/T6ServerConfigs#3]
I try to restrict some attachment, but it does not working. 
Restrict weapons working well, but attachment not.
I try this: dedicated.cfg 
sv_enableItemRestriction 1
sv_restrictionList "restricted.cfg" 
restrict_attachment "dw"

It is a bug or i wrong something?

**Comment by xerxes-at** [comment]
The stock restriction system does not work reliable, the custom one has no support to just ban a attachment, so yeah it is known.

**Comment by xerxes-at** [comment]
It finally happened, the old broken system got replaced by a new shiny one. ec69bbea6d9f98c6595c2b3894cf07210b3832d9
