### ISSUE TITLE
GSC configuration

### ISSUE THREAD

**Issue by res7702** [xerxes-at/T6ServerConfigs#4]
PT6 now has serverside GSC support and I think theres some configuration to do for enabling scripts

**Comment by xerxes-at** [comment]
Place the GSC script in the correct folder and start the server, done. There is no need to change anything as the server will check if a custom file can be loaded every time it loads a gsc file.
We can only replace existing once and can not create completely new files and you need to pre-compile them.
The file structure must be the same as in the FFs (or GSC dumps) relatively seen from ./t6r/data.

Edit Drgn did create a more in depth guide on the [AWOG Forum](https://awog.at/t/96)
